/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.72"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    // testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    // testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // use junit-jupiter-5.6.2
    testImplementation("org.junit.jupiter:junit-jupiter:5.6.2")

    // unit test untuk membuat object tiruan
    testImplementation("org.mockito:mockito-junit-jupiter:3.5.13")
}

// complete configuration junit-jupiter
tasks.named<Test>("test"){
    // untuk grouping test, tanpa integration-test
    useJUnitPlatform {
        // jika ada beberapa tags, pisahkan dengan coma(,)
        excludeTags("integration-test")
    }
}

tasks.register("integration-test", Test::class){
    // untuk grouping test, hanya integration-test
    useJUnitPlatform {
        includeTags("integration-test")
    }
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile::class).all {
    kotlinOptions {
        jvmTarget = "11"
    }
}

application {
    // Define the main class for the application.
    mainClassName = "belajar.kotlin.unit.test.AppKt"
}
